"use client";

import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const Satoshi = localFont({
  src: "../public/fonts/Satoshi-Variable.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={Satoshi.className}>
      <body className={Satoshi.className}>{children}</body>
    </html>
  );
}
